<?php /** @var T4webEmployees\Controller\User\ListViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<div class="page-header">
    <div class="row">
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-users page-header-icon"></i>&nbsp;&nbsp;Employees</h1>

        <div class="col-xs-12 col-sm-8">
            <div class="row">
                <!-- "Create project" button, width=auto on desktops -->
                <div class="pull-right col-xs-12 col-sm-auto">
                    <a style="width: 100%;" class="btn btn-primary btn-labeled" href="<?=$this->url('employee-add');?>">
                        <span class="btn-label icon fa fa-plus"></span>Add employee</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row employees">

    <?php foreach($viewModel->getEmployees()->getTopManagers() as $manager): ?>
        <div class="col-md-6">
            <?= $this->partial('partials/top-manager.phtml', ['manager' => $manager]); ?>
        </div>
    <?php endforeach; ?>

    <?php foreach($viewModel->getEmployees()->getWorkers() as $employee): ?>
        <div class="col-md-3">
            <?= $this->partial('partials/employee.phtml', ['employee' => $employee]); ?>
        </div>
    <?php endforeach; ?>

</div>