<section class="content-header">
    <h1><i class="fa fa-files-o"></i> Pages</h1>
</section>

<section class="content">

    <div class="col-md-12">
        <div class="row">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Create page</h3>
                </div><!-- /.box-header -->

                <form action="<?=$this->url('admin-page-create')?>" method="post">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="title">Title:</label>
                            <input type="text" value="" class="form-control" name="title" />
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            <label for="body">Body:</label>
                            <textarea class="form-control" name="body"></textarea>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button class="btn btn-primary" type="submit">Create</button>
                        <a href="/admin/pages" class="btn btn-default">Cancel and return to list</a>
                    </div>
                </form>

            </div>
        </div>
    </div>

</section>