<?php /** @var T4webPages\Controller\Admin\PageViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<section class="content-header">
    <h1><i class="fa fa-files-o"></i> Pages</h1>
</section>

<section class="content">

    <div class="col-md-12">
        <div class="row">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Create page</h3>
                </div><!-- /.box-header -->

                <form action="<?=$this->url('admin-page-create')?>" method="post">
                    <div class="box-body">
                        <div class="form-group <?=$viewModel->getHasErrorClass('title')?>">
                            <label for="title">Title:</label>
                            <input type="text" value="<?=$viewModel->getFormData('title')?>" class="form-control" name="title" />
                            <?php foreach($viewModel->getErrors('title') as $error): ?>
                                <p class="help-block"><?=$error?></p>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group <?=$viewModel->getHasErrorClass('body')?>">
                            <label for="body">Body:</label>
                            <textarea class="form-control" name="body"><?=$viewModel->getFormData('body')?></textarea>
                            <?php foreach($viewModel->getErrors('body') as $error): ?>
                                <p class="help-block"><?=$error?></p>
                            <?php endforeach; ?>
                        </div>
                    </div>

                    <div class="box-footer">
                        <button class="btn btn-primary" type="submit">Create</button>
                        <a href="/admin/pages" class="btn btn-default">Cancel and return to list</a>
                    </div>
                </form>

            </div>
        </div>
    </div>

</section>